name: calc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

  
jobs:
  # This workflow contains a single job called "build"
  job_my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: add two numbers
        run: echo $((7*50))
